package document

import org.gradle.testkit.runner.GradleRunner
import org.gradle.testkit.runner.TaskOutcome
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Assumptions.assumeTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File

/**
 * Dogfooding functional test (EPIC DOC-BOOK-MULTILANG, US-4) — the multi-language
 * translation against the real private content corpus, **fully offline**.
 *
 * US-2 proved the mechanism on a synthetic book; this gate closes the loop on
 * the *user-visible* outcome at scale: `translateBookAllLanguages` over a real
 * (bounded) subset of the scanned corpus must produce one translated
 * `book-<lang>.adoc` **per requested language**, each keeping every *structural*
 * TOC anchor (D1 — the structure is regenerated by construction), while the
 * source book is never mutated.
 *
 * The fake LLM (`llmMode=fake`) keeps the run metered-free (Règle 2 — no
 * translation is actually performed). The private corpus is consumed read-only
 * (Règle 7): a bounded, real subset is copied into a throw-away TestKit project
 * (Ink Economy Law). The test self-skips (`assumeTrue`) when the corpus is
 * absent.
 */
class BookMultilangContentFunctionalTest {

    companion object {
        private val CONTENT_DIR = File("/home/cheroliv/workspace/office/metiers/FPA")
        private val CONTENT_TOC = File(CONTENT_DIR, "toc.adoc")
        private val CONTENT_SCANS = File(
            CONTENT_DIR,
            "Devenir_Formateur_Professionnel_d_Adultes_FPA_II/scans",
        )

        /** Bounded but real subset — one structured book, a handful of OCR pages. */
        private const val MAX_PAGES = 6

        /** Two target languages is enough to prove the fan-out without cost. */
        private val TARGETS = listOf("en", "de")
    }

    @TempDir
    lateinit var projectDir: File

    @Test
    fun `translateBookAllLanguages produces one structurally intact translated book per language over the real corpus`() {
        assumeTrue(CONTENT_TOC.isFile) { "content TOC not found at ${CONTENT_TOC.absolutePath}" }
        assumeTrue(CONTENT_SCANS.isDirectory) { "content scans not found at ${CONTENT_SCANS.absolutePath}" }

        // --- a reduced but real TOC: the header plus the first MAX_PAGES
        // referenced pages that actually exist in the corpus.
        val tocLines = CONTENT_TOC.readText().lines()
        val header = tocLines.firstOrNull { it.trim().startsWith("|") }
        assumeTrue(header != null) { "the content TOC carries no header row" }
        data class TocEntry(val line: String, val ref: String, val fileName: String)
        val referenced = tocLines.mapNotNull { line ->
            val cells = line.trim().split("|").map { it.trim() }.drop(1)
            if (cells.size < 4) return@mapNotNull null
            val ref = cells[0]
            val fileName = cells[3]
            if (Regex("""\d+(\.\d+)*""").matches(ref) && fileName.endsWith(".adoc") &&
                File(CONTENT_SCANS, fileName).isFile
            ) {
                TocEntry(line, ref, fileName)
            } else {
                null
            }
        }.take(MAX_PAGES)
        assumeTrue(referenced.size >= 3) { "at least three referenced real content pages are required" }
        val tocRefs = referenced.map { it.ref }.toSet()

        projectDir.resolve("content").mkdirs()
        projectDir.resolve("content/toc.adoc").writeText(
            (listOf(header) + referenced.map { it.line }).joinToString("\n") + "\n",
        )
        val pagesDir = projectDir.resolve("content/pages").apply { mkdirs() }
        referenced.forEach { (_, _, name) ->
            File(CONTENT_SCANS, name).copyTo(pagesDir.resolve(name), overwrite = true)
        }

        projectDir.resolve("settings.gradle.kts").writeText(
            """
            rootProject.name = "test-book-multilang-content"
            """.trimIndent(),
        )
        projectDir.resolve("build.gradle.kts").writeText(
            """
            plugins {
                id("education.cccp.document")
            }
            document {
                book {
                    pagesDir.set(layout.projectDirectory.dir("content/pages"))
                    title.set("Content Book")
                    author.set("Content Author")
                    tocFile.set(layout.projectDirectory.file("content/toc.adoc"))
                    sourceLanguage.set("fr")
                    targetLanguages.set(listOf(${TARGETS.joinToString(", ") { "\"$it\"" }}))
                }
                translation {
                    llmMode.set("fake")
                }
            }
            """.trimIndent(),
        )

        val result = GradleRunner.create()
            .withProjectDir(projectDir)
            .withArguments("translateBookAllLanguages")
            .withPluginClasspath()
            .build()

        assertEquals(
            TaskOutcome.SUCCESS,
            result.task(":translateBookAllLanguages")?.outcome,
            "translateBookAllLanguages must succeed",
        )

        val docsDir = projectDir.resolve("build/docs/document")
        TARGETS.forEach { lang ->
            val book = docsDir.resolve("book-$lang.adoc")
            assertTrue(book.isFile, "book-$lang.adoc must be produced — dir: ${docsDir.listFiles()?.joinToString { it.name }}")

            val content = book.readText()
            assertTrue(content.contains("[${lang.uppercase()}]"), "book-$lang must carry translated content")

            // D1 gate: every *structural* TOC anchor is regenerated (scoped to the
            // TOC refs — an OCR page may carry a non-structural in-band anchor
            // artefact legitimately dropped by the lossy pivot, piège #39).
            val missing = tocRefs - anchorRefs(content)
            assertTrue(missing.isEmpty(), "book-$lang must keep every structural [[ref]] anchor (D1), missing: $missing")
            assertTrue(content.contains(":doctype: book"), "book-$lang must keep the doctype")
            assertTrue(content.contains("toc::[]"), "book-$lang must keep the toc block")
        }

        assertFalse(
            docsDir.resolve("book.adoc").exists(),
            "the multi-language task must not produce or mutate the untranslated book.adoc",
        )
    }

    private fun anchorRefs(content: String): Set<String> =
        Regex("""\[\[([^\]]+)\]\]""").findAll(content).map { it.groupValues[1] }.toSet()
}
