package document.translation

/**
 * Parses the YAML produced by [PivotYamlRenderer] back into a [PivotArticle].
 *
 * The format is a strict, deterministic YAML subset generated by the renderer:
 * every block type is prefixed with `type:`, scalar values are JSON-quoted via
 * [PivotYamlRenderer]. This parser is the round-trip counterpart used by the
 * tree translation mode (whole-article single LLM call).
 */
class PivotYamlParser {

    fun parse(yaml: String): PivotArticle {
        val lines = yaml.lines().filter { it.isNotBlank() }
        var i = 0
        require(lines.isNotEmpty() && lines[0].trim() == "article:") {
            "Invalid pivot YAML: expected 'article:' root, got: ${lines.firstOrNull()}"
        }
        i = 1

        var frontmatter = PivotFrontmatter("", "", "", "")
        val blocks = mutableListOf<PivotBlock>()

        while (i < lines.size) {
            val line = lines[i]
            if (line.startsWith("  frontmatter:")) {
                val parsed = parseFrontmatter(lines, i + 1)
                frontmatter = parsed.first
                i = parsed.second
            } else if (line.startsWith("  blocks:")) {
                val parsed = parseBlocks(lines, i + 1)
                blocks.addAll(parsed.first)
                i = parsed.second
            } else {
                i++
            }
        }

        return PivotArticle(frontmatter, blocks)
    }

    private fun parseFrontmatter(lines: List<String>, start: Int): Pair<PivotFrontmatter, Int> {
        var title = ""
        var date = ""
        var type = ""
        var status = ""
        var author = ""
        val jbake = mutableMapOf<String, String>()
        val asciidoc = mutableMapOf<String, String>()
        var i = start
        var section: String? = null

        while (i < lines.size && lines[i].startsWith("    ")) {
            val line = lines[i].trim()
            when {
                line.startsWith("title:") -> title = unquote(line.removePrefix("title:").trim())
                line.startsWith("date:") -> date = unquote(line.removePrefix("date:").trim())
                line.startsWith("type:") -> type = unquote(line.removePrefix("type:").trim())
                line.startsWith("status:") -> status = unquote(line.removePrefix("status:").trim())
                line.startsWith("author:") -> author = unquote(line.removePrefix("author:").trim())
                line.startsWith("jbake_attributes:") -> {
                    section = "jbake"
                    i++
                    while (i < lines.size && lines[i].trim().startsWith("\"")) {
                        val idx = lines[i].indexOf(':')
                        val k = unquote(lines[i].substring(0, idx).trim())
                        val v = unquote(lines[i].substring(idx + 1).trim())
                        jbake[k] = v
                        i++
                    }
                    continue
                }
                line.startsWith("asciidoc_attributes:") -> {
                    section = "asciidoc"
                    i++
                    while (i < lines.size && lines[i].trim().startsWith("\"")) {
                        val idx = lines[i].indexOf(':')
                        val k = unquote(lines[i].substring(0, idx).trim())
                        val v = unquote(lines[i].substring(idx + 1).trim())
                        asciidoc[k] = v
                        i++
                    }
                    continue
                }
            }
            i++
        }

        val fm = PivotFrontmatter(
            title = title,
            date = date,
            type = type,
            status = status,
            author = author,
            jbakeAttributes = jbake,
            asciidocAttributes = asciidoc
        )
        return fm to i
    }

    private fun parseBlocks(lines: List<String>, start: Int): Pair<List<PivotBlock>, Int> {
        val blocks = mutableListOf<PivotBlock>()
        var i = start

        while (i < lines.size) {
            val line = lines[i]
            if (line.startsWith("  blocks:")) { i++; continue }
            if (!line.startsWith("    - ")) break

            val parsed = parseBlock(lines, i, indent = "    ")
            blocks.add(parsed.first)
            i = parsed.second
        }

        return blocks to i
    }

    private fun parseBlock(lines: List<String>, start: Int, indent: String): Pair<PivotBlock, Int> {
        var i = start
        val first = lines[i].trim().removePrefix("- ")
        require(first.startsWith("type: ")) { "Expected 'type:' in block, got: $first" }
        val type = first.removePrefix("type: ").trim()
        i++

        return when (type) {
            "heading" -> {
                var level = 2
                var text = ""
                var translatable = true
                while (i < lines.size && lines[i].startsWith("$indent  ")) {
                    val l = lines[i].trim()
                    when {
                        l.startsWith("level:") -> level = l.removePrefix("level:").trim().toInt()
                        l.startsWith("text:") -> text = unquote(l.removePrefix("text:").trim())
                        l.startsWith("translatable:") -> translatable = l.removePrefix("translatable:").trim().toBoolean()
                    }
                    i++
                }
                PivotBlock.Heading(level, text, translatable) to i
            }
            "paragraph" -> {
                val (inlines, next) = parseInlineList(lines, i, "$indent  ")
                PivotBlock.Paragraph(inlines) to next
            }
            "list" -> {
                var ordered = false
                var j = i
                if (j < lines.size && lines[j].trim().startsWith("ordered:")) {
                    ordered = lines[j].trim().removePrefix("ordered:").trim().toBoolean()
                    j++
                }
                // items:
                if (j < lines.size && lines[j].trim().startsWith("items:")) {
                    j++
                    val items = mutableListOf<List<PivotInline>>()
                    while (j < lines.size && lines[j].startsWith("$indent    - ")) {
                        // - inline:
                        val (inlines, next) = parseInlineList(lines, j + 1, "$indent      ")
                        items.add(inlines)
                        j = next
                    }
                    PivotBlock.ListBlock(ordered, items) to j
                } else {
                    PivotBlock.ListBlock(ordered, emptyList()) to j
                }
            }
            "table" -> {
                var cols: String? = null
                var j = i
                if (j < lines.size && lines[j].trim().startsWith("cols:")) {
                    val raw = lines[j].trim().removePrefix("cols:").trim()
                    cols = if (raw == "null") null else unquote(raw)
                    j++
                }
                // header:
                if (j < lines.size && lines[j].trim().startsWith("header:")) {
                    j++
                    val header = mutableListOf<List<PivotInline>>()
                    while (j < lines.size && lines[j].startsWith("$indent    - inline:")) {
                        val (inlines, next) = parseInlineList(lines, j + 1, "$indent      ")
                        header.add(inlines)
                        j = next
                    }
                    // rows:
                    val rows = mutableListOf<List<List<PivotInline>>>()
                    if (j < lines.size && lines[j].trim().startsWith("rows:")) {
                        j++
                        while (j < lines.size && lines[j].startsWith("$indent    - ")) {
                            val cells = mutableListOf<List<PivotInline>>()
                            var k = j
                            while (k < lines.size && lines[k].startsWith("$indent    - ")) {
                                val (inlines, next) = parseInlineList(lines, k + 1, "$indent      ")
                                cells.add(inlines)
                                k = next
                            }
                            rows.add(cells)
                            j = k
                        }
                    }
                    PivotBlock.Table(cols, header, rows) to j
                } else {
                    PivotBlock.Table(cols, emptyList(), emptyList()) to j
                }
            }
            "admonition" -> {
                var kind = "NOTE"
                var j = i
                if (j < lines.size && lines[j].trim().startsWith("kind:")) {
                    kind = lines[j].trim().removePrefix("kind:").trim()
                    j++
                }
                if (j < lines.size && lines[j].trim().startsWith("blocks:")) {
                    j++
                    val inner = mutableListOf<PivotBlock>()
                    while (j < lines.size && lines[j].startsWith("$indent    - ")) {
                        val parsed = parseBlock(lines, j, "$indent    ")
                        inner.add(parsed.first)
                        j = parsed.second
                    }
                    PivotBlock.Admonition(kind, inner) to j
                } else {
                    PivotBlock.Admonition(kind, emptyList()) to j
                }
            }
            "source" -> {
                var language = ""
                var content = ""
                var j = i
                if (j < lines.size && lines[j].trim().startsWith("language:")) {
                    language = unquote(lines[j].trim().removePrefix("language:").trim())
                    j++
                }
                if (j < lines.size && lines[j].trim().startsWith("translatable:")) {
                    j++
                }
                if (j < lines.size && lines[j].trim() == "content: |") {
                    j++
                    val body = StringBuilder()
                    while (j < lines.size && lines[j].startsWith("$indent    ")) {
                        body.appendLine(lines[j].removePrefix("$indent    "))
                        j++
                    }
                    content = body.toString().removeSuffix("\n")
                }
                PivotBlock.Source(language, content) to j
            }
            "hr" -> {
                PivotBlock.Hr to i
            }
            else -> throw IllegalArgumentException("Unknown block type: $type")
        }
    }

    private fun parseInlineList(lines: List<String>, start: Int, indent: String): Pair<List<PivotInline>, Int> {
        val inlines = mutableListOf<PivotInline>()
        var i = start

        while (i < lines.size && lines[i].startsWith("$indent- ")) {
            val raw = lines[i].removePrefix("$indent- ").trim()
            when {
                raw.startsWith("text:") -> {
                    val text = unquote(raw.removePrefix("text:").trim())
                    val (translatable, next) = parseTranslatable(lines, i + 1, indent)
                    inlines.add(PivotInline.Text(text, translatable))
                    i = next
                }
                raw.startsWith("type: bold") -> {
                    val text = nextValue(lines, i + 1, indent, "text")
                    val (translatable, next) = parseTranslatable(lines, i + 2, indent)
                    inlines.add(PivotInline.Bold(text, translatable))
                    i = next
                }
                raw.startsWith("type: code") -> {
                    val text = nextValue(lines, i + 1, indent, "text")
                    val (translatable, next) = parseTranslatable(lines, i + 2, indent)
                    inlines.add(PivotInline.Code(text, translatable))
                    i = next
                }
                raw.startsWith("type: link") -> {
                    val url = nextValue(lines, i + 1, indent, "url")
                    val label = nextValue(lines, i + 2, indent, "label")
                    val (translatable, next) = parseTranslatable(lines, i + 3, indent)
                    inlines.add(PivotInline.Link(url, label, translatable))
                    i = next
                }
                raw.startsWith("type: line_break") -> {
                    i++
                    while (i < lines.size && lines[i].startsWith("$indent  ")) { i++ }
                    inlines.add(PivotInline.LineBreak)
                }
                else -> throw IllegalArgumentException("Unknown inline in YAML: $raw")
            }
        }

        return inlines to i
    }

    private fun parseTranslatable(lines: List<String>, start: Int, indent: String): Pair<Boolean, Int> {
        var i = start
        while (i < lines.size && lines[i].startsWith("$indent  ")) {
            val l = lines[i].trim()
            if (l.startsWith("translatable:")) {
                val v = l.removePrefix("translatable:").trim().toBoolean()
                return v to (i + 1)
            }
            i++
        }
        return true to i
    }

    private fun nextValue(lines: List<String>, start: Int, indent: String, key: String): String {
        var i = start
        while (i < lines.size && lines[i].startsWith("$indent  ")) {
            val l = lines[i].trim()
            if (l.startsWith("$key:")) return unquote(l.removePrefix("$key:").trim())
            i++
        }
        return ""
    }

    private fun unquote(s: String): String {
        var v = s
        if (v.length >= 2 && v.startsWith("\"") && v.endsWith("\"")) {
            v = v.substring(1, v.length - 1)
        }
        return v.replace("\\\"", "\"").replace("\\\\", "\\")
    }
}
