package document

import java.io.File

/**
 * Pure engine that turns a structured [BookTree] into one published translated
 * book file (EPIC DOC-BOOK-MULTILANG, US-2 — decision D5, extracted from the
 * mono-language `translateBook` task).
 *
 * Encapsulates the mechanical chain shared by every target language:
 *
 * 1. translate the **domain** ([BookTranslator]: titles + page bodies) so the
 *    structure is regenerated by construction (DOC-BOOK-TRANSLATE decision D1);
 * 2. re-assemble the translated tree ([BookAssembler]) with the caller's
 *    [BookLayout] strategy (matter policy, navigation, matter breaks);
 * 3. materialise the referenced scans next to the book and re-assemble with a
 *    relative `:imagesdir:` ([BookImageMaterializer], DOC-BOOK-IMAGES);
 * 4. write the result to [BookTranslationRequest.outputFile].
 *
 * The engine is Gradle-free (plain [File] I/O, like [BookImageMaterializer]),
 * so it is unit-testable and reused verbatim by the mono-language
 * `translateBook` task and the multi-language `translateBookAllLanguages` task
 * — a single source of truth for the translation-publication contract.
 *
 * Ink Economy Law: nothing here decides *whether* to run (blank target,
 * `skipExisting`, plan emptiness are the caller's concerns); it only performs
 * the work it is asked to do.
 */
class BookTranslationRunner(
    private val translator: BookTranslator,
) {

    /**
     * Translates [tree] into [BookTranslationRequest.targetLanguage], assembles
     * the regenerated structure and writes it to
     * [BookTranslationRequest.outputFile].
     *
     * @return the assembled [BookAssemblyResult] (already written to disk)
     */
    fun translateAndPublish(request: BookTranslationRequest): BookAssemblyResult {
        val translated = translator.translate(
            tree = request.tree,
            resolveContent = request.resolveContent,
            sourceLanguage = request.sourceLanguage,
            targetLanguage = request.targetLanguage,
        )

        val baseLayout = BookLayout(
            emitMatterBreaks = request.matterBreaks,
            matterPolicy = request.matterPolicy,
            emitNavigation = request.navigation,
        )

        val assembled = BookAssembler.assemble(
            tree = translated.tree,
            layout = baseLayout,
            title = request.title,
            author = request.author,
            resolveContent = translated.bodyResolver,
        )

        // Mirror `assembleBook`: when photos are configured the translated book
        // is illustrated by the referenced scans, copied next to the book with a
        // relative `:imagesdir:` (EPIC DOC-BOOK-IMAGES).
        val imageDir = request.photosDir ?: request.pagesDir
        val referenced = BookImageMaterializer.resolveTargets(assembled.content, imageDir)
        val result = if (referenced.isEmpty()) {
            assembled
        } else {
            BookImageMaterializer.materialise(referenced, request.outputFile.parentFile)
            BookAssembler.assemble(
                tree = translated.tree,
                layout = baseLayout.copy(imagesDir = BookImageMaterializer.IMAGES_DIR),
                title = request.title,
                author = request.author,
                resolveContent = translated.bodyResolver,
            )
        }

        result.writeTo(request.outputFile)
        return result
    }
}

/**
 * One translation-publication unit: the source book tree, the language pair,
 * the layout knobs and the destination file.
 *
 * @property tree the source structured book tree
 * @property resolveContent maps a [BookSection] to its OCR-ed AsciiDoc body
 * @property pagesDir directory of the OCR-ed pages (fallback image source)
 * @property photosDir optional directory of the original scans (image source)
 * @property title the book title (level-0 header)
 * @property author the book author (`:author:` attribute)
 * @property sourceLanguage the language the book is written in
 * @property targetLanguage the language to translate to (never blank here)
 * @property matterPolicy how front/back matter is classified and required
 * @property matterBreaks emit a hard page break at matter transitions
 * @property navigation emit previous / next cross-references
 * @property outputFile where the assembled translated book is written
 */
data class BookTranslationRequest(
    val tree: BookTree,
    val resolveContent: (BookSection) -> String,
    val pagesDir: File,
    val photosDir: File?,
    val title: String,
    val author: String,
    val sourceLanguage: String,
    val targetLanguage: String,
    val matterPolicy: MatterPolicy,
    val matterBreaks: Boolean,
    val navigation: Boolean,
    val outputFile: File,
)
