package document

import java.io.File

/**
 * Visual theme applied to the document during multi-format conversion.
 *
 * Ubiquitous language: a [DocumentTheme] carries the theme files (YML, CSS, logo)
 * that [DocumentConverter] injects as AsciidoctorJ attributes (`:stylesheet:`,
 * `:pdf-theme:`, `:epub-stylesheet:`, `:pdf-front-cover-image:`) at conversion time.
 *
 * DOC-10: the theme is not a separate task — it is applied by the conversion task.
 * The theme files are versioned in the project, not generated by the plugin.
 * Fallback: an empty [DocumentTheme] uses AsciidoctorJ defaults.
 */
data class DocumentTheme(
    val pdfTheme: File? = null,
    val htmlStylesheet: File? = null,
    val epubStylesheet: File? = null,
    val logo: File? = null,
) {

    fun isEmpty(): Boolean =
        pdfTheme == null && htmlStylesheet == null && epubStylesheet == null && logo == null

    /**
     * Builds the AsciidoctorJ attributes map for the given [format].
     *
     * - HTML: `stylesheet` -> htmlStylesheet path
     * - PDF: `pdf-theme` -> pdfTheme path, `pdf-front-cover-image` -> logo path
     * - EPUB: `epub-stylesheet` -> epubStylesheet path
     * - DOCBOOK / MANPAGE: no theme attributes (unsupported by AsciidoctorJ)
     */
    fun toAttributes(format: DocumentFormat): Map<String, String> {
        if (isEmpty()) return emptyMap()
        return when (format) {
            DocumentFormat.HTML -> htmlStylesheet?.let { mapOf("stylesheet" to it.absolutePath) } ?: emptyMap()
            DocumentFormat.PDF -> buildMap {
                pdfTheme?.let { put("pdf-theme", it.absolutePath) }
                logo?.let { put("pdf-front-cover-image", it.absolutePath) }
            }
            DocumentFormat.EPUB -> epubStylesheet?.let { mapOf("epub-stylesheet" to it.absolutePath) } ?: emptyMap()
            DocumentFormat.DOCBOOK -> emptyMap()
            DocumentFormat.MANPAGE -> emptyMap()
        }
    }
}